### ISSUE TITLE
org.jpos.iso.IFA_LLLCHAR: Problem unpacking field 105 (java.lang.RuntimeException: Required 28 but just got 27 bytes) unpacking field=105, consumed=323

### ISSUE THREAD

**Issue by VeenaPDas** [tilln/jmeter-iso8583#22]
Hi Team,

When we try to post ISO8583 messgae from Jmeter ISO8583 plugin using xml configuration file. The transaction has been posted to server successfully , while receiving back response from server jmeter is not able to parse the response message due to filed length error. When i analysed the server  logs   application is response without truncating any characters but when jmeter is receiving response the last character has been truncated due to this all the transaction which we posted from jmeter is getting accumulated into failure count.

Kindly guide me to get rid of this error.

[Jmeter_log.txt](https://github.com/tilln/jmeter-iso8583/files/4723295/Jmeter_log.txt)

**Comment by tilln** [comment]
Is this consistently happening for all messages?
Is it always one byte short as in the attached sample or does it vary?

**Comment by VeenaPDas** [comment]
Yes,its happening for all messages
Yes, its always one byte short. It does not vary.

**Comment by tilln** [comment]
As I doubt this has anything to do with JMeter or this plugin, I would recommend try reproduce this issue with the jPOS client simulator (instructions [here](https://jpos.org/blog/2013/07/setting-up-the-client-simulator/)). If it happens there as well it may be a jPOS issue.
What may also be worthwhile is ruling out any network infrastructure in between the server host and JMeter host, for example by running JMeter closer to or ideally directly on the server.

**Comment by VeenaPDas** [comment]
Its not possible to run jMETER on the host server. I will try to setup client simulator and post the transactions to the host.

**Comment by VeenaPDas** [comment]
Still not able to resolve the issue. We tried using TCP sampler also, but no luck!!

**Comment by VeenaPDas** [comment]
When we run load test , we are getting below error 
2020-06-04 12:57:17,864 ERROR n.c.b.j.i.ISO8583Sampler: Send failed org.jpos.iso.ISOException: Duplicate key 'jmeter-1f109138-send.0200000000000000101125717.req' detected
org.jpos.iso.ISOException: Duplicate key 'jmeter-1f109138-send.0200000000000000101125717.req' detected

Any idea about this error??

**Comment by tilln** [comment]
That means that jPOS has trouble with matching outgoing requests and incoming responses based on unique keys it assigns each message.
By default, the message fields MTI, [41 and 11](https://github.com/jpos/jPOS/blob/v2_1_4/jpos/src/main/java/org/jpos/q2/iso/QMUX.java#L46) are used, which you should be able to identify when looking at the value `0200000000000000101125717`.

Two options to fix this:
- Either vary those fields in the messages your send, if you can,
- Or, if you can't, define other fields that you _can_ vary and that can uniquely identify each message. 

For the second option, you'll need plugin version 1.1 and look at the Connection Configuration's ["Mux Settings"](https://github.com/tilln/jmeter-iso8583#config).

**Comment by VeenaPDas** [comment]
020-06-11 04:44:37,255 DEBUG n.c.b.j.i.ISO8583Sampler: sampleStart
2020-06-11 04:44:37,349 DEBUG n.c.b.j.i.Q2: (channel/204.130.42.239:18858) [send] Out: 0200 239 B0000001
2020-06-11 04:44:37,395 DEBUG n.c.b.j.i.Q2: (channel/204.130.42.239:18858) [got-message-length] 340
2020-06-11 04:44:37,395 DEBUG n.c.b.j.i.Q2: (channel/204.130.42.239:18858) [got-message-trailler] 32
2020-06-11 04:44:37,395 ERROR n.c.b.j.i.Q2: (channel/204.130.42.239:18858) [receive] org.jpos.iso.IFA_LLLCHAR: Problem unpacking field 105 (java.lang.RuntimeException: Required 14 but just got 13 bytes) unpacking field=105, consumed=323
org.jpos.iso.ISOException: org.jpos.iso.IFA_LLLCHAR: Problem unpacking field 105 (java.lang.RuntimeException: Required 14 but just got 13 bytes) unpacking field=105, consumed=323
                at org.jpos.iso.ISOBasePackager.unpack(ISOBasePackager.java:340) ~[jpos-2.1.4.jar:2.1.4]
                at org.jpos.iso.ISOMsg.unpack(ISOMsg.java:479) ~[jpos-2.1.4.jar:2.1.4]
                at org.jpos.iso.BaseChannel.unpack(BaseChannel.java:976) ~[jpos-2.1.4.jar:2.1.4]
                at org.jpos.iso.BaseChannel.receive(BaseChannel.java:746) [jpos-2.1.4.jar:2.1.4]
                at org.jpos.q2.iso.ChannelAdaptor$Receiver.run(ChannelAdaptor.java:332) [jpos-2.1.4.jar:2.1.4]
                at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

The length of incoming message is 340 Bytes,

2020-06-11 04:44:37,395 DEBUG n.c.b.j.i.Q2: (channel/204.130.42.239:18858) [got-message-length] 340
2020-06-11 04:44:37,395 DEBUG n.c.b.j.i.Q2: (channel/204.130.42.239:18858) [got-message-trailler] 32  --> this is the last character missing in the incoming message, while parsing.

Any idea about this??

**Comment by VeenaPDas** [comment]
It Would be more helpful if you provide some solution,!! :)

**Comment by tilln** [comment]
I'm sorry that I can't be more helpful as you haven't provided a lot of details.

It [looks like](https://github.com/jpos/jPOS/blob/v2_1_4/jpos/src/main/java/org/jpos/iso/channel/BASE24TCPChannel.java#L110) your `BASE24TCPChannel` is interpreting that last message byte as trailer.
Are you sure you are using the right Channel?
