### ISSUE TITLE
(org.jpos.q2.iso.ChannelAdaptor) error starting service

### ISSUE THREAD

**Issue by Ranypho** [tilln/jmeter-iso8583#98]
Dear team,

I am new JMeter and ISO8583, I try to follow in your guideline but it is error as below :

2024-06-12 10:31:30,918 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2024-06-12 10:31:30,918 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2024-06-12 10:31:30,923 INFO n.c.b.j.i.Q2: (Q2.system) Q2 started, deployDir=D:\apache-jmeter-5.6.2\apache-jmeter-5.6.2\bin\deploy, environment=default
2024-06-12 10:31:30,945 ERROR n.c.b.j.i.Q2: (org.jpos.q2.iso.ChannelAdaptor) error starting service
2024-06-12 10:31:30,945 ERROR n.c.b.j.i.Q2: (org.jpos.q2.iso.ChannelAdaptor) org.jpos.core.ConfigurationException: Error reading D:/apache-jmeter-5.6.2/apache-jmeter-5.6.2/bin/ISO8583 Sampler.jmx (org.jpos.iso.ISOException: Error reading D:/apache-jmeter-5.6.2/apache-jmeter-5.6.2/bin/ISO8583 Sampler.jmx (org.xml.sax.SAXParseException; systemId: file:///D:/apache-jmeter-5.6.2/apache-jmeter-5.6.2/bin/ISO8583%20Sampler.jmx; lineNumber: 2; columnNumber: 16; Document is invalid: no grammar found.))
org.jpos.core.ConfigurationException: org.jpos.core.ConfigurationException: Error reading D:/apache-jmeter-5.6.2/apache-jmeter-5.6.2/bin/ISO8583 Sampler.jmx (org.jpos.iso.ISOException: Error reading D:/apache-jmeter-5.6.2/apache-jmeter-5.6.2/bin/ISO8583 Sampler.jmx (org.xml.sax.SAXParseException; systemId: file:///D:/apache-jmeter-5.6.2/apache-jmeter-5.6.2/bin/ISO8583%20Sampler.jmx; lineNumber: 2; columnNumber: 16; Document is invalid: no grammar found.))
	at org.jpos.q2.QFactory.setConfiguration(QFactory.java:382) ~[jpos-2.1.8.jar:2.1.8]
	at org.jpos.q2.iso.ChannelAdaptor.newChannel(ChannelAdaptor.java:202) ~[jpos-2.1.8.jar:2.1.8]
	at org.jpos.q2.iso.ChannelAdaptor.initChannel(ChannelAdaptor.java:253) ~[jpos-2.1.8.jar:2.1.8]
	at org.jpos.q2.iso.ChannelAdaptor.startService(ChannelAdaptor.java:76) [jpos-2.1.8.jar:2.1.8]
	at org.jpos.q2.QBeanSupport.start(QBeanSupport.java:137) [jpos-2.1.8.jar:2.1.8]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_411]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_411]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_411]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_411]
	at sun.reflect.misc.Trampoline.invoke(Unknown Source) [?:1.8.0_411]
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_411]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_411]
	at sun.reflect.misc.MethodUtil.invoke(Unknown Source) [?:1.8.0_411]
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(Unknown Source) [?:1.8.0_411]
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(Unknown Source) [?:1.8.0_411]
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(Unknown Source) [?:1.8.0_411]
	at com.sun.jmx.mbeanserver.PerInterface.invoke(Unknown Source) [?:1.8.0_411]
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(Unknown Source) [?:1.8.0_411]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(Unknown Source) [?:1.8.0_411]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(Unknown Source) [?:1.8.0_411]
	at org.jpos.q2.QFactory.startQBean(QFactory.java:176) [jpos-2.1.8.jar:2.1.8]
	at nz.co.breakpoint.jmeter.iso8583.ISO8583Config.deployAndStart(ISO8583Config.java:364) [jmeter-iso8583-1.3.jar:?]
	at nz.co.breakpoint.jmeter.iso8583.ISO8583Config.startChannelAdaptor(ISO8583Config.java:283) [jmeter-iso8583-1.3.jar:?]
	at nz.co.breakpoint.jmeter.iso8583.ISO8583Config.testStarted(ISO8583Config.java:467) [jmeter-iso8583-1.3.jar:?]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:246) [ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:424) [ApacheJMeter_core.jar:5.6.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_411]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_411]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_411]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_411]
2024-06-12 10:31:30,947 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2024-06-12 10:31:31,183 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2024-06-12 10:31:31,183 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2024-06-12 10:31:31,183 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2024-06-12 10:31:31,183 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=30 delayedStart=false
2024-06-12 10:31:31,183 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2024-06-12 10:31:31,183 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2024-06-12 10:31:31,184 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2024-06-12 10:31:31,185 ERROR n.c.b.j.i.ISO8583Config: Packager configuration error
org.xml.sax.SAXParseException: Document is invalid: no grammar found.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) ~[xercesImpl-2.12.2.jar:?]
	at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source) ~[xercesImpl-2.12.2.jar:?]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.12.2.jar:2.12.2]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.12.2.jar:2.12.2]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.12.2.jar:2.12.2]
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) ~[xercesImpl-2.12.2.jar:2.12.2]
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source) ~[xercesImpl-2.12.2.jar:2.12.2]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.12.2.jar:2.12.2]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.12.2.jar:2.12.2]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.12.2.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.12.2.jar:?]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.12.2.jar:?]
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.12.2.jar:?]
	at org.jpos.iso.packager.GenericPackager.readFile(GenericPackager.java:201) ~[jpos-2.1.8.jar:2.1.8]
	at org.jpos.iso.packager.GenericPackager.<init>(GenericPackager.java:116) ~[jpos-2.1.8.jar:2.1.8]
	at nz.co.breakpoint.jmeter.iso8583.ISO8583Config.createPackager(ISO8583Config.java:133) [jmeter-iso8583-1.3.jar:?]
	at nz.co.breakpoint.jmeter.iso8583.ISO8583Sampler.addTestElement(ISO8583Sampler.java:106) [jmeter-iso8583-1.3.jar:?]
	at org.apache.jmeter.threads.TestCompiler.configureWithConfigElements(TestCompiler.java:314) [ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.threads.TestCompiler.configureSampler(TestCompiler.java:101) [ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:560) [ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) [ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) [ApacheJMeter_core.jar:5.6.2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_411]
2024-06-12 10:31:31,187 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'ISO8583 Sampler'.
java.lang.NullPointerException: null
	at org.jpos.iso.ISOMsg.pack(ISOMsg.java:467) ~[jpos-2.1.8.jar:2.1.8]
	at nz.co.breakpoint.jmeter.iso8583.ISO8583Sampler.sample(ISO8583Sampler.java:156) ~[jmeter-iso8583-1.3.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) [ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) [ApacheJMeter_core.jar:5.6.2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_411]
2024-06-12 10:31:31,187 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2024-06-12 10:31:31,187 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2024-06-12 10:31:31,187 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2024-06-12 10:31:31,188 INFO n.c.b.j.i.Q2: (Q2.system) shutting down
2024-06-12 10:31:31,188 INFO n.c.b.j.i.Q2: (Q2.system) shutdown done
2024-06-12 10:31:31,188 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)

**Comment by tilln** [comment]
Your packager definition file is incorrect.

**Comment by Ranypho** [comment]
hi @tilln 

please kindly help advice ?

below is the configure:
![image](https://github.com/tilln/jmeter-iso8583/assets/172231020/8d2048ad-5e8e-4e5b-b60e-0a3f9fdf2dfa)
![image](https://github.com/tilln/jmeter-iso8583/assets/172231020/db6a67ef-f1d0-4eb3-9b39-7f05fcfd0339)

**Comment by tilln** [comment]
Please have a look at the documentation [here](https://github.com/tilln/jmeter-iso8583?tab=readme-ov-file#prerequisites) and [here](https://github.com/jpos/jPOS/blob/v2_1_8/doc/src/asciidoc/ch04/genericpackager.adoc).
Referencing a JMeter jmx file as a Packager Configuration file makes no sense at all.

**Comment by Ranypho** [comment]
Dear @tilln,

could you  verify my JMeter jmx below: 

[ISO8583 test.zip](https://github.com/user-attachments/files/15799361/ISO8583.test.zip)

**Comment by tilln** [comment]
Please have a look at the documentation [here](https://github.com/tilln/jmeter-iso8583?tab=readme-ov-file#prerequisites) and [here](https://github.com/jpos/jPOS/blob/v2_1_8/doc/src/asciidoc/ch04/genericpackager.adoc).
Referencing a JMeter jmx file as a Packager Configuration file makes no sense at all.

**Comment by Ranypho** [comment]
could you help provide JMeter jmx file that correct ?

**Comment by tilln** [comment]
Ok, trying to help here make you read and understand the documentation.
You do understand what is required?
That you need a Packager configuration file that represents your test system's ISO8583 messaging specifications?
I can't help with providing that I'm afraid.
That file would typically have the extension .xml (not .jmx), so perhaps you are confusing things there.

**Comment by Ranypho** [comment]
Dear tilln,

Thank for recommend, I am fix xml done.

could you help advice Bitmap missing?
this is the correct Bitmap : 0200F2300011088080000000000004000000

![image](https://github.com/tilln/jmeter-iso8583/assets/172231020/46b94ec4-9263-489a-8dbc-504d93574053)

**Comment by tilln** [comment]
@Ranypho 
You haven't provided enough information for me to advise anything.

I can only assume that the Bitmap is generated automatically by the Packager, so if it is incorrect then it is likely that your message contains different fields than are expected (13, 15, 16, 17).

Also, I doubt that the first 2 bytes `02 00` are part of the Bitmap but they look like the MTI (field 0).

**Comment by Ranypho** [comment]
thank for advice
